version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  deposito:
    build: ./deposito
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "app.py", "deposito"]

  fabrica:
    build: ./fabrica
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "app.py", "fabrica"]

  ordens:
    build: ./ordens
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "app.py", "ordens"]

  estoque:
    build: ./estoque
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "app.py", "estoque"]

  linha_producao:
    build: ./linha_producao
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "app.py", "linha_producao"]

  fornecedor:
    build: ./fornecedor
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["python", "app.py", "fornecedor"]